### ISSUE TITLE
a smiley from iphone breaks the text

### ISSUE THREAD

**Issue by hostellerie** [Geeklog-Plugins/forum#23] opened 2016-11-03 18:14 UTC
Smileys iphone are not kept and the text after the smiley is not retained when submiting a forum post

Hello 😁 world 
will only retain
Hello

**Comment by eSilverStrike** [comment] 2016-11-03 18:29
As far as you can tell this happens for iPhones only?

**Comment by hostellerie** [comment] 2016-11-03 18:43
The issue was reported by an user and I ask him to send me the message by email. I can reproduce the issue on a PC if I try to post (copy paste) the content with the smiley

**Comment by eSilverStrike** [comment] 2016-11-03 19:03
Can you email me the message so I can check? I don't have an iPhone so I wouldn't be able to test with one.

**Comment by eSilverStrike** [comment] 2016-11-04 10:45
Copying "Hello 😁 world" above also creates the issue. The emoji seems to be not filtered out by Geeklog (or at least made able to store in the db). The same issue happens when adding a comment to a story. In Geeklog 2.1.2 the following error is reported:

E_USER_ERROR(256) - 1366: Incorrect string value: '\xF0\x9F\x98\x81 w...' for column 'comment' at row 1 @ \geeklog\system\databases\mysqli.class.php line 352
Call Stack

# Function    File    Line

1   trigger_error   \geeklog\system\databases\mysqli.class.php  352
2   dbQuery \geeklog\system\lib-database.php    206
3   DB_query    \geeklog\public_html\forum\createtopic.php  286

array(3) {
  ["sql"]=>
  string(225) "INSERT INTO gl_forum_topic (forum,name,date,lastupdated,subject,comment,postmode,ip,mood,uid,pid,sticky,locked) VALUES ('1','Admin','1478256167',1478256167,'Test','Hello 😁 world', 'text','192.168.1.224','','2','0','0','0')"
  ["ignore_errors"]=>
  int(0)
  ["result"]=>
  bool(false)
}

**Comment by eSilverStrike** [comment] 2016-11-08 16:34
Okay this has been fixed in part in Geeklog Core by adding checks to COM_applyFilters. The problem is not all fields (like name and comment (which is the main forum topic field)) use this function. Specifc checks will need to be added when creating a topic for these fields.

**Closed as completed** 2016-11-08 16:55 UTC
Labels: bug
